INSERT INTO CURRENCY_EXCHANGE(CONVERSION_MULTIPLE,  	ID,  	CURRENCY_FROM,  	CURRENCY_TO,  	ENVIRONMENT  )
VALUES(65,1001,'USD','INR', '');
INSERT INTO CURRENCY_EXCHANGE(CONVERSION_MULTIPLE,  	ID,  	CURRENCY_FROM,  	CURRENCY_TO,  	ENVIRONMENT  )
VALUES(75,1002,'EUR','INR', '');
INSERT INTO CURRENCY_EXCHANGE(CONVERSION_MULTIPLE,  	ID,  	CURRENCY_FROM,  	CURRENCY_TO,  	ENVIRONMENT  )
VALUES(25,1003,'AUD','INR', '');